### ISSUE TITLE
平がDockerを使いたいらしいです。

### ISSUE THREAD

**Issue by tsuyoshi628** [Piko-Piko-Pon-Taro/Remollege#45]

**Comment by pahalce** [comment]
api/config/config.json でホスト名をサービス名に変更すれば解決する。
[WIP]switch host name #42で西井が対応中

**Comment by tsuyoshi628** [comment]
わーい

**Comment by pahalce** [comment]
@turunasi これconfig.jsonとdocker-composeのdevelopment_in_dockerの記述のところだけいったんプッシュしたらまずい？
