### ISSUE TITLE
video通話まわりが問題なく動作するようにする

### ISSUE THREAD

**Issue by tsuyoshi628** [Piko-Piko-Pon-Taro/Remollege#51]
- [x] skywayのエラーがあったときにデバッグレベルによってapikeyが表示されちゃうので、デバッグレベル抑えたら表示されないか一応確認してほしい

**Comment by pahalce** [comment]
skywayのエラーじゃなさそうだったからnodeの方っぽい
nodeの環境変われば出ないか見ないといけない

**Comment by pahalce** [comment]
そんなことなかった
エラー文書き換えてAPIキー出さないように変更
