### ISSUE TITLE
見た目調整

### ISSUE THREAD

**Issue by tsuyoshi628** [Piko-Piko-Pon-Taro/Remollege#75]
- [x] 全体
  - [x] カラーの調整
  - [x] titleをclient-client->Remollegeに変更
  - [x] faviconを設定
  - [x] 誘導(indexで「建物選んでね」、buildingsで「お部屋を選んでね」てきな)->最悪toastでいい->常時上部に表示でもよい(headers内でもいいかも)
- [x] header
  - [x] ~~iconを設定~~ -> 一旦いいや。
  - [x] iconとuserIconにリンクなどを付与
- [x] login
  - [x] レスポンシブ
- [x] index, buildings
  - [x] cardの左右マージン
  - [x] ~~cardのテキストが長い時は途中で切るようにして、高さを固定する~~ -> 一番大きい高さに合わせる
  - [x] cardをレスポンシブにしよう
- [x] rooms
  - [x] tableの大きさをレスポンシブでいい感じにする
  - [x] ~~video部分のレスポンシブ~~ -> #110 で対応する

**Comment by pahalce** [comment]
英語と日本語混在してるのに基準つけたほうがいいかも

**Comment by pahalce** [comment]
通話のコントローラーbottomnav使ってることでクリックしたときに選択中のが赤くなるけど、挙動がおかしいから直す

**Comment by pahalce** [comment]
ビデオ通話人数増えた時どうするか
通話画面のUI名前の表示とか調整
